wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1658680328
    t:
      1:
      - 55
      3:
      - 3
      - 8
      4: 3.10.4
      5: 0.12.21
      8:
      - 1
      - 5
      10:
      - 9
